services:
  pgdatabase:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      -"./ny_taxi_postgres_data:/var/lib/postgresql/data"
    ports:
      -"5432:5432"
    pgadmin:
      image: dpage/pgadmin4
      environment: 
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - "8080:80"


#docker run -it -e POSTGRES_USER="root" -e POSTGRES_PASSWORD="root" -v ${pwd}/ny_taxi_postgres_data:/var/lib/postgresql/data -p 5432:5432 postgres:16.4
# data https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page


